### ISSUE TITLE
my_ims

### ISSUE THREAD

**Issue by archaga** [jbpcasoy/buksu_imd_dms#256]
![image](https://user-images.githubusercontent.com/68852130/226267708-212b7d0a-bdb1-4981-8d16-d6a81b758eb3.png)

1. What is the purpose of "Reviewed As" if you are the owner of the IM? You can't review your own IM's, you cant be a peer reviewer, or, chair, or coordinator?

**Comment by archaga** [comment]
2. it is redundant to the review status indicators.

**Comment by jbpcasoy** [comment]
remove on /my_ims page only

**Comment by jbpcasoy** [comment]
done along with redundant columns on other tables
