### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by archaga** [jbpcasoy/buksu_imd_dms#262]
![image](https://user-images.githubusercontent.com/68852130/226492310-4473cf0b-6b93-4983-98af-987866752de6.png)

1. Notification bell should only have the indicator (red circle) if there's new notification. Otherwise, the indicator should be hidden.

**Comment by archaga** [comment]
![image](https://user-images.githubusercontent.com/68852130/226492895-2d2896aa-e3e5-4fae-94df-6667a4d2f937.png)

2. All unread/unviewed notifications must have a background color (bg-blue-500) to emphasize the new notifs, from the old one.

**Comment by jbpcasoy** [comment]
done
